name: Trigger auto deployment for gateway-api-kacperbanasik-cicd

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'nodejs-microservices/packages/gateway-api/**'
    - '.github/workflows/gateway-api-kacperbanasik-cicd-AutoDeployTrigger-fb7ef39d-1742-4453-99ba-43ec4b77326b.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.GATEWAYAPIKACPERBANASIKCICD_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.GATEWAYAPIKACPERBANASIKCICD_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.GATEWAYAPIKACPERBANASIKCICD_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/nodejs-microservices
          dockerfilePath: packages/gateway-api/Dockerfile
          registryUrl: rejestrkb.azurecr.io
          registryUsername: ${{ secrets.GATEWAYAPIKACPERBANASIKCICD_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.GATEWAYAPIKACPERBANASIKCICD_REGISTRY_PASSWORD }}
          containerAppName: gateway-api-kacperbanasik-cicd
          resourceGroup: szkolenie-rg
          imageToBuild: rejestrkb.azurecr.io/gateway-api-kacperbanasik-cicd:${{ github.sha }}
          environmentVariables: >
            SETTINGS_API_URL=https://settings-api-kacperbanasik-cicd.happyriver-c3b70016.westus2.azurecontainerapps.io
            DICE_API_URL=https://dice-api-kacperbanasik-cicd.happyriver-c3b70016.westus2.azurecontainerapps.io


